{"cells":[{"cell_type":"markdown","source":["#README Classifier\n\n1.\tG. A. A. Prana, C. Treude, F. Thung, T. Atapattu, and D. Lo, “Categorizing the Content of GitHub README Files - Empirical Software Engineering,” SpringerLink, 12-Oct-2018. [Online]. Available: https://link.springer.com/article/10.1007/s10664-018-9660-3. [Accessed: 11-Dec-2021].\n2.\tGprana. “Gprana/READMEClassifier.” GitHub, https://github.com/gprana/READMEClassifier.\n\n\n\n##Install modules and make imports"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"4fc51a51-6004-4cc3-bd46-94737ba173f3"}}},{"cell_type":"code","source":["%sh\npip install nltk\npip install click\npip install html2text\npip install lxml\npip install markdown2\npip install numpy\npip install pandas\npip install python-dateutil\npip install pytz\npip install regex\npip install scikit-learn\npip install scipy\npip install six\npip install sklearn\npip install soupsieve\npip install threadpoolctl\npip install tqdm\npip install bs4\npip install beautifulsoup4\npip install --upgrade pip\npython -m nltk.downloader all"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"ae30e29b-c512-4b96-93a8-2cfc72191348"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"code","source":["# standard modules\nimport pandas as pd\nimport numpy as np\nimport nltk\nimport re\n\n# feature engineering\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.preprocessing import MultiLabelBinarizer\nfrom sklearn.preprocessing import LabelBinarizer\n\n# classifiers\nfrom sklearn.multiclass import OneVsRestClassifier\nfrom sklearn.svm import LinearSVC\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.naive_bayes import GaussianNB\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.ensemble import BaggingClassifier\nfrom sklearn.ensemble import ExtraTreesClassifier\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import AdaBoostClassifier\nfrom sklearn.ensemble import GradientBoostingClassifier\nfrom sklearn.ensemble import HistGradientBoostingClassifier\n\n\n# measures\nfrom sklearn.model_selection import cross_val_predict\nfrom sklearn.model_selection import cross_val_score\nfrom sklearn.model_selection import cross_validate\nfrom sklearn.metrics import classification_report\n\n# other\nfrom joblib import Parallel\nfrom joblib import delayed\nfrom sklearn.utils import resample\nfrom sklearn.utils.validation import check_is_fitted\nfrom sklearn.base import BaseEstimator, clone\n\nnltk.download('words')"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"804ece5a-8eaf-42b0-9bf9-3f7f114eceab"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["##Preparation\n\n###Code for deriving heuristic features"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"0845b2c9-264d-4917-b270-58ae52a4b9df"}}},{"cell_type":"code","source":["class Heuristic_Feature:\n  \"\"\"\n  Class for deriving heuristic features from input text\n\n  Naming convention:\n    heur_<x>_<y>_<number>\n      <x> = c if meant for use in content text, h if meant for use with header\n      <y> = k if uses keyword matching, s if uses text statistics (e.g. word count), c if combination\n  \"\"\"\n\n  def heur_c_k_001(self, input_text):\n    if ('report bugs' in input_text.lower()) or ('reporting bugs' in input_text.lower()):\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_002(self, input_text):\n    if ' is a ' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_003(self, input_text):\n    if '@abstr_code_section' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_004(self, input_text):\n    if 'attempts to' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_005(self, input_text):\n    if 'inspired by' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_006(self, input_text):\n    if 'install ' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_007(self, input_text):\n    if 'reasons' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  # Do not use lower() because we want to capture \"Added\" at beginning of sentence\n  def heur_c_k_008(self, input_text):\n    if 'Added ' in input_text:\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_009(self, input_text):\n    if 'copyright' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_010(self, input_text):\n    if '@abstr_mailto' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_011(self, input_text):\n    if 'you can ' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  # Check if the text comprises solely of @abstr_code_section\n  def heur_c_k_012(self, input_text):\n    if '@abstr_code_section' == input_text.lower().strip():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_013(self, input_text):\n    if 'About' in input_text:\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_014(self, input_text):\n    if 'be sure to' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_015(self, input_text):\n    if 'Download' in input_text:\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_016(self, input_text):\n    if 'overview' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_017(self, input_text):\n    if 'get started' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_018(self, input_text):\n    if 'reasons' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_019(self, input_text):\n    if 'dependenc' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_020(self, input_text):\n    if 'rerun' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_021(self, input_text):\n    if 'you''ll be able' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_022(self, input_text):\n    if 'you must' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_c_k_023(self, input_text):\n    if 'previous version' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_001(self, input_text):\n    if 'configur' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_002(self, input_text):\n    if 'what' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_003(self, input_text):\n    if 'why' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_004(self, input_text):\n    if 'approach' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_005(self, input_text):\n    if 'bugs' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_006(self, input_text):\n    if 'contrib' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_007(self, input_text):\n    if 'credit' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_008(self, input_text):\n    if 'feature' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_009(self, input_text):\n    if 'install' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_010(self, input_text):\n    if 'intro' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_011(self, input_text):\n    if 'licen' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_012(self, input_text):\n    if 'objective' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_013(self, input_text):\n    if 'request' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_014(self, input_text):\n    if 'requirement' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_015(self, input_text):\n    if 'resource' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_016(self, input_text):\n    if 'setting' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_017(self, input_text):\n    if 'setup' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_018(self, input_text):\n    if 'started' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_019(self, input_text):\n    if 'usage' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_020(self, input_text):\n    if 'version' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_021(self, input_text):\n    if 'welcome' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_022(self, input_text):\n    if 'what is' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_023(self, input_text):\n    if 'overview' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_024(self, input_text):\n    if 'basic' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_025(self, input_text):\n    if 'roadmap' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_026(self, input_text):\n    if 'todo' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_027(self, input_text):\n    if 'example' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_028(self, input_text):\n    if 'about' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  def heur_h_k_029(self, input_text):\n    if 'reference' in input_text.lower():\n      return 1\n    else:\n      return 0\n\n  # Return 1 if string is single non-English word\n  # WARNING: For speed, instantiate the word set outside and pass it as parameter,\n  # so that instantiation will be done once for each program run\n  # instead of once for each row this heuristic is applied to\n  def heur_h_c_001(self, input_text, words=None):\n    lcase_input_text = input_text.lower()\n    s = lcase_input_text.split(' ')\n    if len(s) != 1:\n      return 0\n    else:\n      if words is None:\n        words = set(nltk.corpus.words.words())\n      if s[0] in words:\n        return 0\n      else:\n        return 1\n    return 0\n\n  # Returns 1 if a word in heading text is in repo name, or the other way around\n  def heur_h_c_002(self, heading_text, repo_url):\n    heading_words = heading_text.lower().split(' ')\n    repo_name = re.sub(r\"http(s)*:\\/\\/www\\.github\\.com\\/.+\\/\", '', repo_url)\n    repo_name = repo_name.replace('.', ' ').replace('-', ' ')\n    repo_name_words = repo_name.lower().split(' ')\n    match = [val for val in heading_words if val in repo_name_words]\n    if len(match) > 0:\n      return 1\n    else:\n      return 0\n\n  # See whether text comprises entirely of ASCII characters\n  def heur_c_s_001(self, input_text):\n    try:\n      input_text.encode(encoding='utf-8').decode('ascii')\n    except UnicodeDecodeError:\n      return 0\n    else:\n      return 1\n\n  # Generate DataFrame of derived features using DataFrames of some initial features\n  def derive_features_using_heuristics(self, url_corpus, heading_text_corpus, content_corpus):\n    derived_features = pd.DataFrame()\n    derived_features['heur_c_k_001'] = [self.heur_c_k_001(x) for x in content_corpus]\n    derived_features['heur_c_k_002'] = [self.heur_c_k_002(x) for x in content_corpus]\n    derived_features['heur_c_k_003'] = [self.heur_c_k_003(x) for x in content_corpus]\n    derived_features['heur_c_k_004'] = [self.heur_c_k_004(x) for x in content_corpus]\n    derived_features['heur_c_k_005'] = [self.heur_c_k_005(x) for x in content_corpus]\n    derived_features['heur_c_k_006'] = [self.heur_c_k_006(x) for x in content_corpus]\n    derived_features['heur_c_k_007'] = [self.heur_c_k_007(x) for x in content_corpus]\n    derived_features['heur_h_k_001'] = [self.heur_h_k_001(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_002'] = [self.heur_h_k_002(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_003'] = [self.heur_h_k_003(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_004'] = [self.heur_h_k_004(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_005'] = [self.heur_h_k_005(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_006'] = [self.heur_h_k_006(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_007'] = [self.heur_h_k_007(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_008'] = [self.heur_h_k_008(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_009'] = [self.heur_h_k_009(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_010'] = [self.heur_h_k_010(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_011'] = [self.heur_h_k_011(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_012'] = [self.heur_h_k_012(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_013'] = [self.heur_h_k_013(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_014'] = [self.heur_h_k_014(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_015'] = [self.heur_h_k_015(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_016'] = [self.heur_h_k_016(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_017'] = [self.heur_h_k_017(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_018'] = [self.heur_h_k_018(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_019'] = [self.heur_h_k_019(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_020'] = [self.heur_h_k_020(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_021'] = [self.heur_h_k_021(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_022'] = [self.heur_h_k_022(x) for x in heading_text_corpus]\n    derived_features['heur_c_s_001'] = [self.heur_c_s_001(x) for x in heading_text_corpus]\n\n    # Batch 02\n    derived_features['heur_c_k_008'] = [self.heur_c_k_008(x) for x in content_corpus]\n    derived_features['heur_c_k_009'] = [self.heur_c_k_009(x) for x in content_corpus]\n    derived_features['heur_c_k_010'] = [self.heur_c_k_010(x) for x in content_corpus]\n    derived_features['heur_c_k_011'] = [self.heur_c_k_011(x) for x in content_corpus]\n    derived_features['heur_c_k_012'] = [self.heur_c_k_012(x) for x in content_corpus]\n    derived_features['heur_c_k_013'] = [self.heur_c_k_013(x) for x in content_corpus]\n    derived_features['heur_h_k_023'] = [self.heur_h_k_023(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_024'] = [self.heur_h_k_024(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_025'] = [self.heur_h_k_025(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_026'] = [self.heur_h_k_026(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_027'] = [self.heur_h_k_027(x) for x in heading_text_corpus]\n    words = set(nltk.corpus.words.words())\n    derived_features['heur_h_c_001'] = [self.heur_h_c_001(x, words) for x in heading_text_corpus]\n    derived_features['heur_h_c_002'] = [self.heur_h_c_002(x, y) for x, y in zip(heading_text_corpus, url_corpus)]\n\n    # Batch 03\n    derived_features['heur_c_k_014'] = [self.heur_c_k_014(x) for x in content_corpus]\n    derived_features['heur_c_k_015'] = [self.heur_c_k_015(x) for x in content_corpus]\n    derived_features['heur_c_k_016'] = [self.heur_c_k_016(x) for x in content_corpus]\n    derived_features['heur_c_k_017'] = [self.heur_c_k_017(x) for x in content_corpus]\n    derived_features['heur_c_k_018'] = [self.heur_c_k_018(x) for x in content_corpus]\n    derived_features['heur_c_k_019'] = [self.heur_c_k_019(x) for x in content_corpus]\n    derived_features['heur_c_k_020'] = [self.heur_c_k_020(x) for x in content_corpus]\n    derived_features['heur_c_k_021'] = [self.heur_c_k_021(x) for x in content_corpus]\n    derived_features['heur_c_k_022'] = [self.heur_c_k_022(x) for x in content_corpus]\n    derived_features['heur_c_k_023'] = [self.heur_c_k_023(x) for x in content_corpus]\n    derived_features['heur_h_k_028'] = [self.heur_h_k_028(x) for x in heading_text_corpus]\n    derived_features['heur_h_k_029'] = [self.heur_h_k_029(x) for x in heading_text_corpus]\n\n    return derived_features"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"1bbd5c16-8179-4abd-9a4e-0a38ded43ce4"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###Code for OneVsRestClassifier"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"f8ff2098-5060-426b-8f8d-21d387f94199"}}},{"cell_type":"code","source":["class _ConstantPredictor(BaseEstimator):\n  def fit(self, X, y):\n    self.y_ = y\n    return self\n\n  def predict(self, X):\n    check_is_fitted(self, 'y_')\n    return np.repeat(self.y_, X.shape[0])\n\n  def decision_function(self, X):\n    check_is_fitted(self, 'y_')\n    return np.repeat(self.y_, X.shape[0])\n\n  def predict_proba(self, X):\n    check_is_fitted(self, 'y_')\n    return np.repeat([np.hstack([1 - self.y_, self.y_])], X.shape[0], axis=0)\n\n\ndef _fit_binary(estimator, X, y, classes=None):\n  \"\"\"\n  Fit a single binary estimator\n  \"\"\"\n  unique_y = np.unique(y)\n\n  if len(unique_y) == 1:\n    if classes is not None:\n      if y[0] == -1:\n        c = 0\n      else:\n        c = y[0]\n    estimator = _ConstantPredictor().fit(X, unique_y)\n\n  else:\n    estimator = clone(estimator)\n    estimator.fit(X, y)\n\n  return estimator\n\n\nclass OneVsRestClassifierBalance(OneVsRestClassifier):\n  def fit(self, X, y):\n    self.label_binarizer_ = LabelBinarizer(sparse_output=True)\n    Y = self.label_binarizer_.fit_transform(y)\n    Y = Y.tocsc()\n    self.classes_ = self.label_binarizer_.classes_\n    totalIns = Y.shape[0]\n    XBal = []\n    YBal = []\n\n    for i in range(len(self.label_binarizer_.classes_)):\n      if len(y.shape) > 1:\n        # Matrix\n        curIdxs = Y[:, i].nonzero()[0]\n      else:\n        curIdxs = Y.nonzero()[0]\n\n      baseX = X[curIdxs, :]\n\n      if len(y.shape) > 1:\n        # Matrix\n        baseY = y[curIdxs, :]\n      else:\n        # array, e.g. due to testing classifier performance for single label prediction\n        baseY = y[curIdxs]\n\n      tempX = X\n      tempY = y\n      imbalancedIns = baseX.shape[0]\n      numDup = totalIns/imbalancedIns - 1\n\n      for j in range(int(numDup)):\n        tempX = np.vstack((tempX, baseX))\n\n        if len(y.shape) > 1:\n          tempY = np.vstack((tempY, baseY))\n\n        else:\n          tempY = np.concatenate((tempY, baseY))\n\n      numAdd = totalIns % imbalancedIns\n      tempX = np.vstack(\n        (tempX, resample(baseX, n_samples=numAdd, random_state=0)))\n\n      if len(y.shape) > 1:\n        tempY = np.vstack(\n          (tempY, resample(baseY, n_samples=numAdd, random_state=0)))\n\n      else:\n        tempY = np.concatenate(\n          (tempY, resample(baseY, n_samples=numAdd, random_state=0)))\n\n      XBal.append(tempX)\n\n      if len(y.shape) > 1:\n        YBal.append(tempY[:, i])\n\n      else:\n        YBal.append(tempY)\n\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(delayed(_fit_binary)(self.estimator, XBal[i], YBal[i], classes=[\"not %s\" % self.label_binarizer_.classes_[i], self.label_binarizer_.classes_[i]]) for i in range(len(YBal)))\n    return self"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"4b66e44a-cddc-4756-bf9f-0ac51746231b"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###Loading data\nLoading the old dataset"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"56bc09ec-7e1c-4ab7-8055-ac0011fd7a89"}}},{"cell_type":"code","source":["def read_CSV_to_DF(filepath):\n  \"\"\"\n  Reads a csv file into a spark dataframe\n  and returns Pandas dataframe\n  \"\"\"\n  df = (\n        sqlContext\n        .read.format(\"csv\")\n        .option(\"header\", \"true\")\n    \n        .load(filepath)\n          )\n  \n  return df.toPandas()\n \n\n# importing files from DBFS\ndf = read_CSV_to_DF('/FileStore/FinalProject/old_and_new_data-1.csv')\n \n# cast the some columns to int\ndf['file_id'] = df['file_id'].astype(int)\ndf['section_id'] = df['section_id'].astype(int)"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"94c79ae4-ba6a-41d8-a075-fb2713b4fa0e"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["##Feature Engineering\n###Extracting statistical features using TF-IDF"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"41020426-6bb3-4f56-bdd2-eca012367565"}}},{"cell_type":"code","source":["heading_plus_content_corpus = df['abstracted_heading_plus_content']\n\ntfidf = TfidfVectorizer(ngram_range=(1,1), analyzer='word', stop_words='english')\ntfidfX = tfidf.fit_transform(heading_plus_content_corpus)\nfeatures_tfidf = pd.DataFrame(tfidfX.todense())\nfeatures_tfidf.columns = tfidf.get_feature_names()"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"7b0fb94f-5a7a-4380-8786-20a0a46bc5f8"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###Extracting heuristic features using Heuristic_Feature class"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"6d341d5e-6289-48e5-9c80-2773b9797c0e"}}},{"cell_type":"code","source":["content_corpus = df['content_text_w_o_tags']\nheading_text_corpus = df['heading_text']\nurl_corpus = df['url']\nheuristic = Heuristic_Feature()\nderived_features = heuristic.derive_features_using_heuristics(url_corpus, heading_text_corpus, content_corpus)"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"050efc11-bc7e-4c7a-afd2-f986fdd7f7f3"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###Combining features together"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"6ef7d784-dd65-42bc-9155-1f4223c407bb"}}},{"cell_type":"code","source":["features_combined = pd.concat([features_tfidf, derived_features], axis=1)"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"c462bc76-fc9c-489b-99b0-538d126b6c6f"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###Encode the target vector"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"e5f6bfb1-fee5-4916-b77c-2d58709b81d2"}}},{"cell_type":"code","source":["# Transform the target vector y\nlabel_set = ['-','1','3','4','5','6','7','8']             # Class '2' has been merged into class '1'\nlabels = [str(x).split(',') for x in df['section_code']]\n\nmlb = MultiLabelBinarizer(classes=label_set)\nlabels_matrix = mlb.fit_transform(labels)"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"15a63980-ecbe-4b19-819d-a731832e4f1a"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["##Cross Validate to find the best model"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"f69004f5-d75d-4452-b067-9614fcff8ba1"}}},{"cell_type":"code","source":["def cross_validate_model(classifier, classifier_name):\n  print(f'Running experiment for {classifier_name}')\n  print('Getting per-class scores')\n  y_pred = cross_val_predict(classifier, features_combined.values, labels_matrix, cv=10)\n\n  print('Computing overall results')\n  scores_f1 = cross_val_score(classifier, features_combined.values, labels_matrix, cv=10, scoring='f1_weighted').mean()\n\n  print(classification_report(labels_matrix, y_pred, digits=3))\n  print('f1_weighted : {0}'.format(scores_f1))"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"d395a1ef-107a-4798-a7df-49a83a55e889"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"data":"","errorSummary":"","metadata":{},"errorTraceType":null,"type":"ipynbError","arguments":{}}},"output_type":"display_data","data":{"text/html":["<style scoped>\n  .ansiout {\n    display: block;\n    unicode-bidi: embed;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    word-break: break-all;\n    font-family: \"Source Code Pro\", \"Menlo\", monospace;;\n    font-size: 13px;\n    color: #555;\n    margin-left: 4px;\n    line-height: 19px;\n  }\n</style>"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###1. LinearSVC"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"cd1125bf-0de9-4fd1-a46a-72fdee883460"}}},{"cell_type":"code","source":["cross_validate_model(OneVsRestClassifierBalance(LinearSVC()), 'LinearSVC()')"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"424879fb-c24f-4ee1-be06-f18ecbc5cbfb"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"Running experiment for LinearSVC()\nGetting per-class scores\nComputing overall results\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n              precision    recall  f1-score   support\n\n           0      0.537     0.756     0.628       422\n           1      0.554     0.541     0.548       652\n           2      0.809     0.849     0.828      2234\n           3      0.682     0.682     0.682       151\n           4      0.785     0.708     0.745       274\n           5      0.597     0.605     0.601       811\n           6      0.857     0.833     0.845       108\n           7      0.155     0.672     0.252        61\n\n   micro avg      0.675     0.740     0.706      4713\n   macro avg      0.622     0.706     0.641      4713\nweighted avg      0.700     0.740     0.716      4713\n samples avg      0.675     0.717     0.682      4713\n\nf1_weighted : nan\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"ansi","arguments":{}}},"output_type":"display_data","data":{"text/plain":["Running experiment for LinearSVC()\nGetting per-class scores\nComputing overall results\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n              precision    recall  f1-score   support\n\n           0      0.537     0.756     0.628       422\n           1      0.554     0.541     0.548       652\n           2      0.809     0.849     0.828      2234\n           3      0.682     0.682     0.682       151\n           4      0.785     0.708     0.745       274\n           5      0.597     0.605     0.601       811\n           6      0.857     0.833     0.845       108\n           7      0.155     0.672     0.252        61\n\n   micro avg      0.675     0.740     0.706      4713\n   macro avg      0.622     0.706     0.641      4713\nweighted avg      0.700     0.740     0.716      4713\n samples avg      0.675     0.717     0.682      4713\n\nf1_weighted : nan\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/svm/_classes.py\", line 228, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr',\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###2. RandomForest"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"b9b746cb-4967-412b-99da-b7d0d02c2d39"}}},{"cell_type":"code","source":["cross_validate_model(OneVsRestClassifierBalance(RandomForestClassifier()), 'RandomForestClassifier()')"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"25547856-1613-4495-9fc4-ba38b7a3d38e"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"Running experiment for RandomForestClassifier()\nGetting per-class scores\nComputing overall results\n              precision    recall  f1-score   support\n\n           0      0.513     0.744     0.607       422\n           1      0.748     0.400     0.521       652\n           2      0.814     0.857     0.835      2234\n           3      0.882     0.444     0.590       151\n           4      0.902     0.540     0.676       274\n           5      0.720     0.502     0.592       811\n           6      0.919     0.528     0.671       108\n           7      0.119     0.623     0.201        61\n\n   micro avg      0.713     0.680     0.696      4713\n   macro avg      0.702     0.580     0.587      4713\nweighted avg      0.763     0.680     0.700      4713\n samples avg      0.655     0.664     0.651      4713\n\nf1_weighted : 0.6308957564173909\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"ansi","arguments":{}}},"output_type":"display_data","data":{"text/plain":["Running experiment for RandomForestClassifier()\nGetting per-class scores\nComputing overall results\n              precision    recall  f1-score   support\n\n           0      0.513     0.744     0.607       422\n           1      0.748     0.400     0.521       652\n           2      0.814     0.857     0.835      2234\n           3      0.882     0.444     0.590       151\n           4      0.902     0.540     0.676       274\n           5      0.720     0.502     0.592       811\n           6      0.919     0.528     0.671       108\n           7      0.119     0.623     0.201        61\n\n   micro avg      0.713     0.680     0.696      4713\n   macro avg      0.702     0.580     0.587      4713\nweighted avg      0.763     0.680     0.700      4713\n samples avg      0.655     0.664     0.651      4713\n\nf1_weighted : 0.6308957564173909\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###3. Naive Bayes"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"bc5d22ef-da75-46ab-bfb5-6f1ef3fca0fe"}}},{"cell_type":"code","source":["cross_validate_model(OneVsRestClassifierBalance(GaussianNB()), 'GaussianNB()')"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"0eea0067-5ffb-48f6-9500-98a2ee89aff8"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"Running experiment for GaussianNB()\nGetting per-class scores\nComputing overall results\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n              precision    recall  f1-score   support\n\n           0      0.420     0.701     0.525       422\n           1      0.142     0.420     0.212       652\n           2      0.590     0.809     0.683      2234\n           3      0.127     0.470     0.201       151\n           4      0.175     0.456     0.253       274\n           5      0.240     0.560     0.336       811\n           6      0.077     0.315     0.124       108\n           7      0.108     0.344     0.164        61\n\n   micro avg      0.325     0.654     0.434      4713\n   macro avg      0.235     0.510     0.312      4713\nweighted avg      0.396     0.654     0.484      4713\n samples avg      0.405     0.634     0.449      4713\n\nf1_weighted : nan\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"ansi","arguments":{}}},"output_type":"display_data","data":{"text/plain":["Running experiment for GaussianNB()\nGetting per-class scores\nComputing overall results\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n              precision    recall  f1-score   support\n\n           0      0.420     0.701     0.525       422\n           1      0.142     0.420     0.212       652\n           2      0.590     0.809     0.683      2234\n           3      0.127     0.470     0.201       151\n           4      0.175     0.456     0.253       274\n           5      0.240     0.560     0.336       811\n           6      0.077     0.315     0.124       108\n           7      0.108     0.344     0.164        61\n\n   micro avg      0.325     0.654     0.434      4713\n   macro avg      0.235     0.510     0.312      4713\nweighted avg      0.396     0.654     0.484      4713\n samples avg      0.405     0.634     0.449      4713\n\nf1_weighted : nan\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/naive_bayes.py\", line 207, in fit\n    X, y = self._validate_data(X, y)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###4. Logistic Regression"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"ea2b4902-ab6c-4328-a442-1343a006867c"}}},{"cell_type":"code","source":["cross_validate_model(OneVsRestClassifierBalance(LogisticRegression()),'LogisticRegression()')"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"36112ac5-ebed-497b-ae27-c2788f2a6ef1"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"Running experiment for LogisticRegression()\nGetting per-class scores\nComputing overall results\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n              precision    recall  f1-score   support\n\n           0      0.652     0.680     0.666       422\n           1      0.499     0.686     0.578       652\n           2      0.744     0.919     0.822      2234\n           3      0.533     0.742     0.620       151\n           4      0.612     0.737     0.669       274\n           5      0.544     0.714     0.617       811\n           6      0.732     0.833     0.779       108\n           7      0.291     0.377     0.329        61\n\n   micro avg      0.643     0.805     0.715      4713\n   macro avg      0.576     0.711     0.635      4713\nweighted avg      0.647     0.805     0.716      4713\n samples avg      0.689     0.773     0.710      4713\n\nf1_weighted : nan\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"ansi","arguments":{}}},"output_type":"display_data","data":{"text/plain":["Running experiment for LogisticRegression()\nGetting per-class scores\nComputing overall results\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4060, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n              precision    recall  f1-score   support\n\n           0      0.652     0.680     0.666       422\n           1      0.499     0.686     0.578       652\n           2      0.744     0.919     0.822      2234\n           3      0.533     0.742     0.620       151\n           4      0.612     0.737     0.669       274\n           5      0.544     0.714     0.617       811\n           6      0.732     0.833     0.779       108\n           7      0.291     0.377     0.329        61\n\n   micro avg      0.643     0.805     0.715      4713\n   macro avg      0.576     0.711     0.635      4713\nweighted avg      0.647     0.805     0.716      4713\n samples avg      0.689     0.773     0.710      4713\n\nf1_weighted : nan\n/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_sklearn.py\", line 29, in patch_function\n    original_result = original(self, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1344, in fit\n    X, y = self._validate_data(X, y, accept_sparse='csr', dtype=_dtype,\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/base.py\", line 433, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 826, in check_X_y\n    y = column_or_1d(y, warn=True)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n    return f(*args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 864, in column_or_1d\n    raise ValueError(\nValueError: y should be a 1d array, got an array of shape (4061, 8) instead.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n"]},"transient":null}],"execution_count":0},{"cell_type":"markdown","source":["###5. k-Nearest Neighbour"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"d013401e-058d-488c-af0b-09532924f93c"}}},{"cell_type":"code","source":["cross_validate_model(OneVsRestClassifierBalance(KNeighborsClassifier()), 'KNeighborsClassifier()')"],"metadata":{"application/vnd.databricks.v1+cell":{"title":"","showTitle":false,"inputWidgets":{},"nuid":"69bdf64f-d626-4d83-a45b-5cbae302a29e"}},"outputs":[{"output_type":"display_data","metadata":{"application/vnd.databricks.v1+output":{"datasetInfos":[],"data":"Running experiment for KNeighborsClassifier()\nGetting per-class scores\nComputing overall results\n              precision    recall  f1-score   support\n\n           0      0.182     0.874     0.301       422\n           1      0.474     0.468     0.471       652\n           2      0.818     0.620     0.705      2234\n           3      0.421     0.656     0.513       151\n           4      0.585     0.540     0.562       274\n           5      0.369     0.420     0.393       811\n           6      0.661     0.722     0.690       108\n           7      0.032     0.869     0.063        61\n\n   micro avg      0.369     0.589     0.454      4713\n   macro avg      0.443     0.646     0.462      4713\nweighted avg      0.596     0.589     0.560      4713\n samples avg      0.471     0.576     0.499      4713\n\nf1_weighted : 0.5253375257247371\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n","removedWidgets":[],"addedWidgets":{},"metadata":{},"type":"ansi","arguments":{}}},"output_type":"display_data","data":{"text/plain":["Running experiment for KNeighborsClassifier()\nGetting per-class scores\nComputing overall results\n              precision    recall  f1-score   support\n\n           0      0.182     0.874     0.301       422\n           1      0.474     0.468     0.471       652\n           2      0.818     0.620     0.705      2234\n           3      0.421     0.656     0.513       151\n           4      0.585     0.540     0.562       274\n           5      0.369     0.420     0.393       811\n           6      0.661     0.722     0.690       108\n           7      0.032     0.869     0.063        61\n\n   micro avg      0.369     0.589     0.454      4713\n   macro avg      0.443     0.646     0.462      4713\nweighted avg      0.596     0.589     0.560      4713\n samples avg      0.471     0.576     0.499      4713\n\nf1_weighted : 0.5253375257247371\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n/databricks/python/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.\n  _warn_prf(average, modifier, msg_start, len(result))\n"]},"transient":null}],"execution_count":0}],"metadata":{"application/vnd.databricks.v1+notebook":{"notebookName":"ENSF612 Final Project with Original Models - New Data","dashboards":[],"notebookMetadata":{"pythonIndentUnit":2},"language":"python","widgets":{},"notebookOrigID":4424314020178662}},"nbformat":4,"nbformat_minor":0}
